server:
  port: 8080

spring:
  application:
    name: vk-user-service
  security:
    user:
      name: admin
      password: password
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

cache:
  ttl:
    minutes: 1

vk:
  api:
    base-url: https://api.vk.com/method
    version: 5.199
    service-token: ${VK_SERVICE_TOKEN:7b36aff47b36aff47b36aff428780fbca877b367b36aff4139daac0d1ad83670d22b756}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    filter: true

camel:
  springboot:
    main-run-controller: true
  component:
    servlet:
      mapping:
        enabled: true
        path: /api/*

logging:
  level:
    ru.mart.vkservice: DEBUG
    org.apache.camel: WARN