server:
  port: 8080

spring:
  application:
    name: vk-user-service

vk:
  api:
    base-url: https://api.vk.com/method
    version: 5.199
    service-token: ${VK_SERVICE_TOKEN:7b36aff47b36aff47b36aff428780fbca877b367b36aff4139daac0d1ad83670d22b756}

camel:
  springboot:
    main-run-controller: true